coderay:
  coderay_line_numbers: '' 
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
highlighter: rouge
kramdown:
  math_engine: mathjax
  parse_block_html: true
  syntax_highlighter: rouge
markdown: kramdown
name: Vishnu's Personal Website
plugins:
  - jekyll-sitemap
url: "https://vishnu.uk"
permalink: /blogs/:title:output_ext